[start]
command = "node /assets/prestart.mjs && sh /assets/prestart.sh && echo '✔️ Omitiendo php artisan config:cache' && echo '✔️ Iniciando PHP-FPM' && php-fpm -y /assets/php-fpm.conf && echo '✔️ Iniciando Nginx' && exec nginx -c /tmp/nginx.conf"
